server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: 你的邮箱
    password: 你的授权码
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/animal
    username: 你的帐号
    ##你的密码
    password: 你的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#图片存储路径
file:
  upload:
    dir: target/classes/static/img

